Query files
ualr-htcpcp/dcia pull request #76
Opened 2020-12-03 00:24 UTC by I-am-Scott-White

Aggregate wrap added to all aggregate text files.

2020-12-03 03:01 UTC, mdjohns requested changes
Good news: We've got the queries we need for SO Scores by Level, SO Scores by Instructor, and SO Scores by Course. :tada: 

But...
I'm still not sure we have what we need for SO Scores by Student. There is a query for student overall SO scores for a semester (`QueryStudentOverallAverage`), but that's scoped to the whole semester and we need something scoped to a course instance since that will be the page it's displayed on. Example: Given a course instance, like Programming I in Fall 2020, we need to return each student and their average overall SO score. How hard would it be to get that data? 

Also, I'm not sure about Scores by Term either. I've been fighting with the mental concept of that one for weeks, so I might need some more guidance from @jcypret here.

2020-12-03 19:40 UTC, I-am-Scott-White commented on seeders/users.seeder.js
> -const data = [
This issue should be resolved.

2020-12-03 19:41 UTC, I-am-Scott-White commented on queries/QueryByCourse
> +dcia.courseinstances.aggregate([
This issue is resolved

2020-12-04 01:11 UTC, mdjohns commented
> line 97 'studentWorkProject' should be 'studentOutcome'. I think I have been trying to push to fast today.
re-added in 6ed7d03

2020-12-04 01:16 UTC, merged